### PR TITLE
Restyle with Rubocop

### PR DESCRIPTION
**Pull request by coder2000**

### CODE REVIEW

**Comment by nsantiago2719** [comment]
Cool!! Let me merge my commits from staging and let's see on how are we going to fix the conflicts.

**Comment by nsantiago2719** [comment]
Hi @coder2000 thanks for the PR it's great and I've fixed the merge conflicts. But is it possible to add in `.gitignore` the `.idea` folder ?

**Comment by coder2000** [comment]
I can, but it is just the RubyMine project information. It is useful for those who use that IDE to work on the project.

**Comment by nsantiago2719** [comment]
Hmm, yeah a colleague of mine uses RubyMine too. Though I'm not using RubyMine myself, I think it's going to be useful to those who uses RubyMine. Just a favor though can I tag you if ever someone wants to modify those files because as I said I don't use RubyMine and I don't know if it's ok to modify them.

**Comment by coder2000** [comment]
Sure. The .gitignore already ignores the RubyMine files that are personal or have high churn

**Pull request merged**
